### ISSUE TITLE
Problems with loading .env file

### ISSUE THREAD

**Issue by AliBilen123** [sdm4fzi/aas2openapi#1]
# Problems with loading .env file

.env file does only load when loadenv() is used with a specified path. 

Only **loadenv('.env')** does work.

**Comment by SebBehrendt** [comment]
The issue was resolved in the latest release of version [0.1.5]((https://github.com/sdm4fzi/aas2openapi/releases/tag/0.1.5)). From now on, default values are used, if no environment variables are specified. However, it is still possible to load environment variables before starting the middleware. To do so, use values similar to that in the .env.example-file.

**Comment by SebBehrendt** [comment]
The issue was resolved in the latest release of version [0.1.5]((https://github.com/sdm4fzi/aas2openapi/releases/tag/0.1.5)). From now on, default values are used, if no environment variables are specified. However, it is still possible to load environment variables before starting the middleware. To do so, use values similar to that in the .env.example-file.
